---
name: Publish to pypi
on:
  release:
    types: [published]
  workflow_dispatch:
env:
  PYTHON_VERSION: '3.12'

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Hatch
        run: python3 -m pip install hatch
      - name: Install dependencies
        run: hatch build
      - name: Publish to PyPi
        if: "startsWith(github.ref, 'refs/tags/')"
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: |
          hatch publish
